export const useWorkingExperience = () => [
	{
		title: "Senior Software Engineer",
		company: "Mogo Finance Technology Inc.",
		website: "https://www.mogo.ca",
		from: "2023-07",
		to: null,
		descriptions: [
			"Refactored and optimized a legacy application by implementing extensive test coverage, enhancing backend and frontend performance. Rewrote outdated logic, upgraded React Native and associated modules, and decommissioned unused services while rewriting broken legacy programs.",
			"Collaborated closely with Customer Support and FinOps teams to streamline workflows, increasing efficiency through enhancements and new program development tailored to their operational needs.Refactored and upgraded the existing React Native application to improve user experience and code maintainability.",
			"Consolidated multiple outdated admin portals into a single, robust admin platform with access management based on role permissions, providing a more secure and user-friendly interface.",
			"Established a deployment structure using a monorepo with TurboRepo for managing Lambda functions, defined a strategy for database mock-ups in unit tests, and provided CDK deployment examples to support maintainable, modular development.",
		],
		techStacks: [
			"Node.js",
			"Next.js",
			"React Native",
			"Typescript",
			"MongoDb",
			"Github Action",
			"Jest",
			"Design Pattern",
			"AWS Services (Aws Lambda, DynamoDb, SQS, ECS, CDK, etc)",
			"Bitrise",
			"Sentry",
			"DataDog",
		],
	},
	{
		title: "Full Stack Developer",
		company: "Atimi Software",
		website: "https://www.atimi.com",
		from: "2022-08",
		to: "2023-07",
		descriptions: [
			"Designed and developed backend services and an admin portal for a job-matching application, enhancing functionality and ease of use.",
			"Contributed to refactoring legacy code by writing well-structured test cases to ensure code quality and reliability.",
			"Solely gathered insights from the outgoing developer, analyzed the source code, and created detailed documentation covering the entire project architecture, database schema, and infrastructure for handover.",
			"Assisted in onboarding the client’s new developer, providing guidance and sharing project knowledge to facilitate a smooth transition.",
		],
		techStacks: [
			"Node.js",
			"React.js",
			"Typescript",
			"MySql",
			"BitBucket Pipeline",
			"Mocha",
			"Design Pattern",
			"AWS Services (Aws Lambda, Api Gateway, CloudWatch, CloudFormation, SAM, etc)",
			"Agile Methodology",
		],
	},
	{
		title: "Senior Software Engineer",
		company: "Juvo Plus",
		website: "https://www.juvoplus.com",
		from: "2018-09",
		to: "2022-07",
		descriptions: [
			"Led the refactoring and development of key features for legacy systems, including order management, product catalog, marketing automation, and shipping services, ensuring high code quality through comprehensive unit and integration tests",
			"Provided technical guidance and conducted training for new team members, fostering best practices for project success",
			"Designed and implemented a high-performance analytical database using ClickHouse, creating automated cron jobs for safe, efficient data updates with built-in validation checks",
			"Refactored the image resizing system by migrating from a container-based service to AWS Lambda and API Gateway, enabling the system to scale efficiently for high volumes of API requests while significantly improving performance and reducing costs",
			"Collaborated with cross-functional teams to align technical solutions with business goals, delivering impactful features and improving system reliability",
		],
		techStacks: [
			"Node.js",
			"Next.js",
			"MySql",
			"ClickHouse",
			"Circle CI",
			"Docker",
			"Mocha",
			"AWS Services (Lambda, Api Gateway, DynamoDb, etc.)",
			"DataDog",
		],
	},
	{
		title: "Software Engineer Internship",
		company: "Mindlayer",
		website: "https://www.mindlayer.io",
		from: "2017-07",
		to: "2018-09",
		descriptions: [
			"Developed a machine learning portal enabling clients to upload training data and create custom chatbots, improving user experience and AI model integration",
			"Designed and implemented an intuitive drag-and-drop interface for building chatbot flows, leveraging HTML and React.js to enhance functionality and user interactivity",
			"Collaborated closely with the AI team to integrate chatbot models into client mobile applications, including platforms like Facebook Messenger and Telegram, ensuring smooth deployment and user engagement",
		],
		techStacks: [
			"Node.js",
			"Python",
			"React.js",
			"MongoDb",
			"Basic AI",
			"Docker",
			"AWS Services (Lambda, S3, EC2, etc.)",
		],
	},
	{
		title: "Part-time Developer",
		company: "CityU Appslab",
		website: "http://www.cityu.edu.hk/cepie/ip_sale/CityU_Apps_Lab.htm",
		from: "2016-09",
		to: "2017-07",
		descriptions: [
			"Collaborated with healthcare professionals to design and develop a cross-platform mobile application that generates personalized medical reports based on user-provided data through questionnaires",
			"Built an intuitive admin portal allowing doctors to create, customize, and manage questionnaires, and configure medical reports tailored to individual patient responses",
		],
		techStacks: ["Node.js", "React.js", "Express.js", "Docker", "MongoDb"],
	},
];
