export const useWorkingExperience = () => [
	{
		title: "Full Stack Developer",
		company: "Atimi Software",
		website: "https://www.atimi.com",
		from: "2022-08",
		to: null,
		descriptions: [
			"Designed and developed the server for a job matching app and optimized the financial trading app.",
			"Identified and resolved bugs in the existing codebase, and created comprehensive project documentation, including database and architectural structures, to hand over to the client.",
			"Worked on improving the infrastructure of a React Native app to solve a significant memory leak problem, enabling the company to successfully launch to market.",
			"Implemented a scraping and caching mechanism to retrieve quotes for an API server using AWS services, and generated notifications to the app based on changes in the quote data. ",
		],
		techStacks: [
			"Node.js",
			"React.js",
			"Typescript",
			"React Native",
			"MySql",
			"MongoDB",
			"CI/CD",
			"AWS Lambda",
			"AWS Services",
			"Agile Methodology",
		],
	},
	{
		title: "Senior Software Engineer",
		company: "Juvo Plus",
		website: "https://www.juvoplus.com",
		from: "2018-09",
		to: "2022-07",
		descriptions: [
			"Refactored and developed new features for legacy systems, including order, product, marketing, and shipping services, and created well-written unit tests to ensure code quality.",
			"Provided technical guidance and conducted training sessions to onboard new team members to the project, and shared best practices to ensure a successful onboarding experience.",
			"Designed and implemented an analytical database using ClickHouse and created a Cron job to safely update the data while running validation checks.",
			"Successfully refactored the image resize system using Amazon Lambda function to handle a sudden spike in API requests.",
		],
		techStacks: [
			"Node.js",
			"Next.js",
			"Typescript",
			"MySql",
			"MongoDB",
			"CI/CD",
			"Docker",
			"AWS Services",
			"Agile Methodology",
		],
	},
	{
		title: "Software Engineer Internship",
		company: "Mindlayer",
		website: "https://www.mindlayer.io",
		from: "2017-07",
		to: "2018-09",
		descriptions: [
			"Developed machine learning portal enabling clients to input training data and create custom chatbots.",
			"Designed drag and drop interface for building chatbot flows, enhancing HTML & React.js knowledge.",
			"Collaborated with AI team to build and integrate chatbot models into clients' mobile apps, Facebook Messenger, Telegram.",
		],
		techStacks: [
			"Node.js",
			"React.js",
			"MongoDB",
			"Docker",
			"Nginx",
			"AWS Services",
		],
	},
	{
		title: "Part-time Developer",
		company: "CityU Appslab",
		website: "http://www.cityu.edu.hk/cepie/ip_sale/CityU_Apps_Lab.htm",
		from: "2016-09",
		to: "2017-07",
		descriptions: [
			"Cooperated with different doctors to provide a cross-platform mobile application that generates a simple medical report by the user's questionnaire.",
			"Created an admin portal for doctors to design questionnaires and allow them to customize the medical report according to user input.",
		],
		techStacks: [
			"Node.js",
			"React.js",
			"MongoDB",
			"Docker",
			"Nginx",
			"AWS Services",
		],
	},
];
